version: '2'
services:
  kibana: 
    image: docker.elastic.co/kibana/kibana:7.9.1
    ports:
    - 5601:5601
    environment:
      ELASTIC_PASSWORD: changeme
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    ports:
    - 9200:9200
    - 9300:9300
    environment: 
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    networks:
      - es-net
networks:
    es-net:
        driver: bridge